### ISSUE TITLE
Implement "search order" precedence for CLI options ("--", ENV var, profile, default)

### ISSUE THREAD

**Issue by tucker01** [zowe/imperative#34]
Imperative should support a "search order" for option/argument values that includes:

- Values specified on CLI options
- Environment variables
- Profiles
- Default values

# Tasks
 - [x] Create utility to take an option or profile key and return camel case and dash version
Status: @AHumanFromCA
Assigned: None
  - [x] Pass envVariablePrefix into CommandProcessor constructor
Status: Complete
Assigned: @gejohnston 
  - [x] Update command processor to perform "search order" for arguments - just create a stub for ENV var (for now)
Status: Not Started
Assigned: @tucker01 and @ChrisBoehmCA
 - [x]  (Optional) Implement function to get environment value for an option name
Status: Complete
Assigned: @gejohnston 
 - [x]  Write integration test - update/add an imperative test CLI to have a command with an option profile
Status: Complete
Assigned: @ChrisBoehmCA 
 - [x]  Document in Imperative Wiki
Status: Not Started
Assigned: None
 - [x]  Manually validate that existing plugins & CLIs don't break - zowe-cli, sample plugin, CICS, DB2, Endevor, FileMaster
Status: In Progress
Assigned: @gejohnston, @AHumanFromCA , @ChrisBoehmCA 
  - [x] Populate default values for options that were not already populated at the end of "prepare"
Status: Complete
Assigned: @ChrisBoehmCA 
  - [x] Add the aliases to the args object along with the kebab and camel case of the option
Status: Complete
Assigned: @gejohnston

8 point story

**Comment by JTonda** [comment]
Comments from @tucker01  (original imperative repo issue)

Imperative should support a "search order" for option/argument values that includes:

Values specified on CLI options
Environment variables
Profiles
Design
Imperative CLIs use ICommandOptionDefinition to define options to commands. Yargs supplies command handlers with an "Argv" object in the form:

{
  "_":  ["cmd_segment_1", "cmd_segment_2"],
  "$0": "node ...",
  "option_one": "value_one",
  "optionOne": "value_one",
  "option_two": "value_two",
  "optionTwo": "value_two"
}
We will introduce an imperative Argv and deprecate the existing handler parms Argv. This change will allow handlers/CLIs/plugins to remove the @types/yargs and will insulate them from changes to the object made by Yargs.

We will inject options and their values into the imperative Argv as follows:

Yargs will pass the command processor the parsed 'Argv'
For every option defined via ICommandOptionDefinition that is NOT specified in the Argv we will extract the value from (in order):
ENV var for the option
The loaded profile
The imperative Argv will provide keys for options in the form:

argv.optionOne
argv["option-one"]
To maintain equivalence with what Yargs does for the Argv.

If a command has multiple profiles defined, we will use the first profile loaded to extract a matching option value from. If possible, we'll load profiles in the order they appear on the profile config array for the command definition.

With these changes, we cannot allow Yargs to supply default values in the Argv, because we will not be able to distinguish between the user specifying the default value (they want the default) on the option and the default provided by Yargs in the Argv object.

ENV vars will be formed as follows (all uppercase):
<envVariablePrefix>_OPT_<optionName>

The effect of these changes will allow imperative CLIs to mark profiles as optional and users can specify all values for options via CLI options OR ENV var, while still allowing users to persist values in profiles.

These changes MUST NOT break existing plugins/CLIs.

**Comment by tucker01** [comment]
When extracting values from profiles, an option in the form `my-opt` will match both the camel and kebab case properties from the profile:
```
myOpt: false
my-opt: true
```
This was done to maintain compatibility with CLIs that have existing profiles. 

Note: As in the example above, the property that exactly matches the option name takes precedence (`my-opt` will be set to true).

**Comment by tucker01** [comment]
Unless a compelling reason is given to use some other delimiter, we will use space delimited values in environment variable strings to denote arrays (for options of type array). To include a string with spaces as a single element in the array, simply surround in single quotes:
```
CLI_OPT_MY_OPT="test1 test2 'test 3'" 
```
Will result in an args object:
```json
{
   "my-opt": ["test1", "test2", "test 3"]
}
```

**Comment by tucker01** [comment]
The "canonical" form of this issue is misleading. It is a "carry-over" from when the repos were in a different place/state.

The intention of the changes are to enable flexibility in how option arguments are provided to an imperative CLI command. The number of use cases is broad, but specifically, we'd like to enable the ability to use profiles for humans ("set and forget"), while allowing CI/CD pipelines (e.g. Jenkins) to use their own configuration and secure stores (normally ENV vars).
